/** Shared English UI strings for public pages */
export const EN_UI = {
  langBg: "BG",
  langEn: "EN",
  book: "Book",
  bookOnline: "Book online",
  bookVilla: "Book a villa",
  rentPrices: "Rent · prices",
  fullGuide: "Full Pamporovo guide",
  backToGuide: "Full Pamporovo guide",
  moreOnTopic: "More on this topic",
  questionsTopic: "Questions on this topic",
  faqDefault: "Frequently asked questions",
  faqSubtitle:
    "Quick answers on accommodation, pistes, and practical details — useful for search and trip planning.",
  recommendedNearby: "Recommended nearby",
  pisteTable: "Piste table",
  liftTable: "Ski lifts in Pamporovo",
  villaCtaTitle: "Pamporovo Villa — rent a whole villa",
  villaCtaBody:
    "3 private villas on Raykovski Livadi · 2 km from resort centre · fireplace · BBQ · up to 6 guests",
  villaCtaFrom: "from",
  villaCtaPerNight: "/ night",
  seeRent: "See /rent",
  rentPage: "Rental page",
  reserve: "Reserve",
  usefulPages: "Useful pages",
  homeFaqEyebrow: "Booking · prices",
  homeFaqTitle: "Frequently asked questions",
  homeFaqSubtitle:
    "Answers on rental, prices, check-in, and booking — before you fill in the form.",
  stickyReserve: "Book",
  perNight: "/ night",
  pricing: "Prices",
  contact: "Contact",
  amenities: "Amenities",
  gallery: "Gallery",
  otherVillas: "Our other villas",
  summerFrom: "Summer from",
  winterFrom: "Winter from",
  wholeVillaNote: "Whole villa · up to 6 guests",
  googleReview: "Leave a Google review",
  googleReviewShort: "Google review",
  googleMaps: "Google Maps",
  directions: "Get directions",
} as const;
