// Auto-generated by scripts/prepare_photos.py — do not edit by hand
const P = "/photos" as const;

export type SitePhoto = { src: string; alt: string };

export type HeroPhoto = SitePhoto & { webpSrc: string; pngSrc: string };

export const HERO_PHOTO: HeroPhoto = { src: `${P}/hero.jpg`, webpSrc: `${P}/hero.webp`, pngSrc: `${P}/hero.png`, alt: "Хол с камина и трапезария" };

export const VILLA_PHOTOS: Record<
  "villa-edno" | "villa-dve" | "villa-tri",
  SitePhoto
> = {
  "villa-edno": { src: `${P}/villa-edno.jpg`, alt: "Вила под сняг в Пампорово" },
  "villa-dve": { src: `${P}/villa-dve.jpg`, alt: "Хол с камина и трапезария" },
  "villa-tri": { src: `${P}/villa-tri.jpg`, alt: "Златен залез над Родопите" },
};

export const GALLERY_IMAGES: SitePhoto[] = [
  { src: `${P}/23.jpg`, alt: "Планинска гледка от терасата" },
  { src: `${P}/57.jpg`, alt: "Златен залез над Родопите" },
  { src: `${P}/11.jpg`, alt: "Вила под сняг в Пампорово" },
  { src: `${P}/05.jpg`, alt: "Екстериор на вилата през лятото" },
  { src: `${P}/61.jpg`, alt: "Pamporovo Villa — зимен екстериор" },
  { src: `${P}/51.jpg`, alt: "Вила в снежна зима" },
  { src: `${P}/54.jpg`, alt: "Екстериор на вилата през зимата" },
  { src: `${P}/32.jpg`, alt: "Трапезария с изглед към боровата гора" },
  { src: `${P}/08.jpg`, alt: "Хол с камина и трапезария" },
  { src: `${P}/56.jpg`, alt: "Хол с камина и трапезария" },
  { src: `${P}/04.jpg`, alt: "Камина и оборудвана кухня" },
  { src: `${P}/58.jpg`, alt: "Кухня, хол и камина" },
  { src: `${P}/55.jpg`, alt: "Отворено пространство на вилата" },
  { src: `${P}/52.jpg`, alt: "Отворен план — гледка от стълбище" },
  { src: `${P}/02.jpg`, alt: "Вътрешно пространство с камина и стълбище" },
  { src: `${P}/01.jpg`, alt: "Хол и трапезария с каменна стена" },
  { src: `${P}/59.jpg`, alt: "Хол с каменна стена" },
  { src: `${P}/06.jpg`, alt: "Трапезария и хол с дървено стълбище" },
  { src: `${P}/07.jpg`, alt: "Отворено пространство с камина" },
  { src: `${P}/36.jpg`, alt: "Верanda с барбекю" },
  { src: `${P}/34.jpg`, alt: "Оборудвана кухня" },
  { src: `${P}/38.jpg`, alt: "Баня с дърво и камък" },
  { src: `${P}/12.jpg`, alt: "Спалня с изглед към снежната гора" },
  { src: `${P}/13.jpg`, alt: "Уютна спалня с дървена стена" },
  { src: `${P}/60.jpg`, alt: "Спалня с две легла" },
  { src: `${P}/14.jpg`, alt: "Двете спални на вилата" },
  { src: `${P}/03.jpg`, alt: "Коридор към двете спални" },
  { src: `${P}/18.jpg`, alt: "Спалня с дървена табла" },
  { src: `${P}/20.jpg`, alt: "Спалня — отражение в огледалото" },
  { src: `${P}/15.jpg`, alt: "Спалня с дървена стена" },
  { src: `${P}/09.jpg`, alt: "Интериор на Pamporovo Villa" },
  { src: `${P}/10.jpg`, alt: "Pamporovo Villa — интериор" },
  { src: `${P}/16.jpg`, alt: "Интериор на планинската вила" },
  { src: `${P}/17.jpg`, alt: "Вътрешно пространство на вилата" },
  { src: `${P}/19.jpg`, alt: "Pamporovo Villa — интериор" },
  { src: `${P}/21.jpg`, alt: "Интериор на вилата" },
  { src: `${P}/22.jpg`, alt: "Pamporovo Villa" },
  { src: `${P}/24.jpg`, alt: "Изглед от балкона към вилите" },
  { src: `${P}/25.jpg`, alt: "Pamporovo Villa — екстериор" },
  { src: `${P}/26.jpg`, alt: "Pamporovo Villa" },
  { src: `${P}/27.jpg`, alt: "Интериор на вилата" },
  { src: `${P}/28.jpg`, alt: "Pamporovo Villa" },
  { src: `${P}/29.jpg`, alt: "Pamporovo Villa — интериор" },
  { src: `${P}/30.jpg`, alt: "Pamporovo Villa" },
  { src: `${P}/31.jpg`, alt: "Pamporovo Villa" },
  { src: `${P}/33.jpg`, alt: "Pamporovo Villa — интериор" },
  { src: `${P}/35.jpg`, alt: "Pamporovo Villa" },
  { src: `${P}/37.jpg`, alt: "Pamporovo Villa — интериор" },
  { src: `${P}/39.jpg`, alt: "Pamporovo Villa" },
  { src: `${P}/40.jpg`, alt: "Pamporovo Villa — интериор" },
  { src: `${P}/41.jpg`, alt: "Pamporovo Villa" },
  { src: `${P}/42.jpg`, alt: "Pamporovo Villa" },
  { src: `${P}/43.jpg`, alt: "Pamporovo Villa — интериор" },
  { src: `${P}/44.jpg`, alt: "Pamporovo Villa" },
  { src: `${P}/45.jpg`, alt: "Pamporovo Villa" },
  { src: `${P}/46.jpg`, alt: "Pamporovo Villa — интериор" },
  { src: `${P}/47.jpg`, alt: "Pamporovo Villa" },
  { src: `${P}/48.jpg`, alt: "Pamporovo Villa" },
  { src: `${P}/49.jpg`, alt: "Pamporovo Villa — интериор" },
  { src: `${P}/50.jpg`, alt: "Pamporovo Villa" },
  { src: `${P}/53.jpg`, alt: "Pamporovo Villa — интериор" },
];
