// Auto-generated by scripts/prepare_photos.py — do not edit by hand
const P = "/photos" as const;

export type SitePhoto = { src: string; alt: string };

export type HeroPhoto = SitePhoto & { webpSrc: string; mobileWebpSrc: string; pngSrc: string };

export const HERO_PHOTO: HeroPhoto = { src: `${P}/hero.jpg`, webpSrc: `${P}/hero.webp`, mobileWebpSrc: `${P}/hero-mobile.webp`, pngSrc: `${P}/hero.png`, alt: "Хол с камина и трапезария" };

export const VILLA_PHOTOS: Record<
  "villa-edno" | "villa-dve" | "villa-tri",
  SitePhoto
> = {
  "villa-edno": { src: `${P}/villa-1/01.jpg`, alt: "Екстериор на Вила 1 през лятото — градина, люлка и барбекю" },
  "villa-dve": { src: `${P}/villa-2/01.jpg`, alt: "Вила 2 под сняг в Пампорово — зимен екстериор" },
  "villa-tri": { src: `${P}/villa-deluxe/01.jpg`, alt: "Вила Deluxe под сняг в Пампорово — зимен екстериор" },
};

/** Per-villa gallery albums — populated in galleryContent.ts (not auto-split). */
export const GALLERY_IMAGES: SitePhoto[] = [];
