"""Copy and optimize villa photos into client/public/photos/."""
from __future__ import annotations

from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
ASSETS = Path(r"C:\Users\konst\.cursor\projects\h-Apps-PamporovoVilege-pamporovo-villa\assets")
OUT = ROOT / "client" / "public" / "photos"

USER_UUIDS = [
    "1bd3374a", "1eda0194", "0e9221d4", "1f28849d", "4d4e19ac", "2cd74021", "2ac5ffbe",
    "5c095f6b", "33f60e8b", "8bd818c6", "010a0d05", "adbd3555", "ba73bdf2", "55491520",
    "44db30ee", "42c8cd4b", "d2bc6ff8", "44e7183c", "62dbd871", "cf0dee04", "f39516e2",
    "49d9b4a5", "672f8799", "99eda99f", "67c6462c", "909f17d6", "894c1187", "747a0210",
    "614a6213", "369964e1", "90128d3e", "6042fd28", "985da699", "1418985c", "a772da17",
    "a0d7bd0b", "6296b368", "a07d717d", "a8ee4a11", "97507404", "b7b72118", "87688175",
    "ab27e9c0", "cce57b48", "b1a673ae", "a943f539", "b96e2918", "c66f9bf8", "bc13f072",
    "bf7d7210", "cb47a701", "c4cf0b76", "cf827579", "d2befe56", "f561bcec", "e250140f",
    "ec4c5f47", "f08f504a", "f87c433d", "f4002c30", "e231ca93",
]

# Curated Bulgarian alt text per user upload order (1-61)
ALTS: dict[int, str] = {
    1: "Хол и трапезария с каменна стена",
    2: "Вътрешно пространство с камина и стълбище",
    3: "Коридор към двете спални",
    4: "Камина и оборудвана кухня",
    5: "Екстериор на вилата през лятото",
    6: "Трапезария и хол с дървено стълбище",
    7: "Отворено пространство с камина",
    8: "Хол с камина и трапезария",
    9: "Интериор на Pamporovo Villa",
    10: "Pamporovo Villa — интериор",
    11: "Вила под сняг в Пампорово",
    12: "Спалня с изглед към снежната гора",
    13: "Уютна спалня с дървена стена",
    14: "Двете спални на вилата",
    15: "Спалня с дървена стена",
    16: "Интериор на планинската вила",
    17: "Вътрешно пространство на вилата",
    18: "Спалня с дървена табла",
    19: "Pamporovo Villa — интериор",
    20: "Спалня — отражение в огледалото",
    21: "Интериор на вилата",
    22: "Pamporovo Villa",
    23: "Планинска гледка от терасата",
    24: "Изглед от балкона към вилите",
    25: "Pamporovo Villa — екстериор",
    26: "Pamporovo Villa",
    27: "Интериор на вилата",
    28: "Pamporovo Villa",
    29: "Pamporovo Villa — интериор",
    30: "Pamporovo Villa",
    31: "Pamporovo Villa",
    32: "Трапезария с изглед към боровата гора",
    33: "Pamporovo Villa — интериор",
    34: "Оборудвана кухня",
    35: "Pamporovo Villa",
    36: "Верanda с барбекю",
    37: "Pamporovo Villa — интериор",
    38: "Баня с дърво и камък",
    39: "Pamporovo Villa",
    40: "Pamporovo Villa — интериор",
    41: "Pamporovo Villa",
    42: "Pamporovo Villa",
    43: "Pamporovo Villa — интериор",
    44: "Pamporovo Villa",
    45: "Pamporovo Villa",
    46: "Pamporovo Villa — интериор",
    47: "Pamporovo Villa",
    48: "Pamporovo Villa",
    49: "Pamporovo Villa — интериор",
    50: "Pamporovo Villa",
    51: "Вила в снежна зима",
    52: "Отворен план — гледка от стълбище",
    53: "Pamporovo Villa — интериор",
    54: "Екстериор на вилата през зимата",
    55: "Отворено пространство на вилата",
    56: "Хол с камина и трапезария",
    57: "Златен залез над Родопите",
    58: "Кухня, хол и камина",
    59: "Хол с каменна стена",
    60: "Спалня с две легла",
    61: "Pamporovo Villa — зимен екстериор",
}

HERO_NUM = 8
VILLA_NUMS = {"villa-edno": 11, "villa-dve": 8, "villa-tri": 57}

GALLERY_ORDER = [
    23, 57, 11, 5, 61, 51, 54, 32, 8, 56, 4, 58, 55, 52, 2, 1, 59, 6, 7, 36, 34, 38,
    12, 13, 60, 14, 3, 18, 20, 15, 9, 10, 16, 17, 19, 21, 22, 24, 25, 26, 27, 28, 29,
    30, 31, 33, 35, 37, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 53,
]


def resolve(num: int) -> Path:
    uid = USER_UUIDS[num - 1]
    match = next(p for p in ASSETS.glob("*.png") if uid in p.name)
    return match


def save_jpg(src: Path, dest: Path, max_width: int = 1920) -> None:
    with Image.open(src) as im:
        im = im.convert("RGB")
        if im.width > max_width:
            ratio = max_width / im.width
            im = im.resize((max_width, int(im.height * ratio)), Image.Resampling.LANCZOS)
        dest.parent.mkdir(parents=True, exist_ok=True)
        im.save(dest, "JPEG", quality=86, optimize=True)


def main() -> None:
    if OUT.exists():
        for f in OUT.glob("*.jpg"):
            f.unlink()

    index_map: dict[int, str] = {}

    for num in range(1, 62):
        dest = OUT / f"{num:02d}.jpg"
        save_jpg(resolve(num), dest)
        index_map[num] = f"/photos/{num:02d}.jpg"

    hero_src = OUT / "hero.jpg"
    save_jpg(resolve(HERO_NUM), hero_src, max_width=2400)

    for villa_id, num in VILLA_NUMS.items():
        save_jpg(resolve(num), OUT / f"{villa_id}.jpg", max_width=1920)

    lines = [
        "// Auto-generated by scripts/prepare_photos.py — do not edit by hand",
        'const P = "/photos" as const;',
        "",
        "export type SitePhoto = { src: string; alt: string };",
        "",
        f'export const HERO_PHOTO: SitePhoto = {{ src: `${{P}}/hero.jpg`, alt: "{ALTS[HERO_NUM]}" }};',
        "",
        "export const VILLA_PHOTOS: Record<",
        '  "villa-edno" | "villa-dve" | "villa-tri",',
        "  SitePhoto",
        "> = {",
    ]
    for villa_id, num in VILLA_NUMS.items():
        lines.append(f'  "{villa_id}": {{ src: `${{P}}/{villa_id}.jpg`, alt: "{ALTS[num]}" }},')
    lines.append("};")
    lines.append("")
    lines.append("export const GALLERY_IMAGES: SitePhoto[] = [")
    for num in GALLERY_ORDER:
        lines.append(f'  {{ src: `${{P}}/{num:02d}.jpg`, alt: "{ALTS[num]}" }},')
    lines.append("];")

    manifest = ROOT / "client" / "src" / "data" / "photos.ts"
    manifest.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(list(OUT.glob('*.jpg')))} images and {manifest}")


if __name__ == "__main__":
    main()
