#Requires -Version 5.1
# Sets ALL GitHub Actions secrets needed by .github/workflows/deploy.yml
# Requires: gh auth login
$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
Set-Location $Root

function Read-EnvFile([string]$Path) {
  $map = @{}
  if (-not (Test-Path $Path)) { return $map }
  Get-Content $Path | ForEach-Object {
    $line = $_.Trim()
    if (-not $line -or $line.StartsWith("#")) { return }
    $idx = $line.IndexOf("=")
    if ($idx -lt 1) { return }
    $map[$line.Substring(0, $idx).Trim()] = $line.Substring($idx + 1).Trim()
  }
  return $map
}

if (-not (Get-Command gh -ErrorAction SilentlyContinue)) {
  Write-Host "Install GitHub CLI: https://cli.github.com/" -ForegroundColor Yellow
  exit 1
}
gh auth status 2>&1 | Out-Null
if ($LASTEXITCODE -ne 0) { Write-Host "Run: gh auth login" -ForegroundColor Yellow; exit 1 }

$deploy = Read-EnvFile (Join-Path $Root ".deploy.env")
$prod   = Read-EnvFile (Join-Path $Root ".env.production.local")

function Set-Secret([string]$Name, [string]$Value) {
  if ([string]::IsNullOrWhiteSpace($Value)) {
    Write-Host "  SKIP $Name (empty)" -ForegroundColor Yellow
    return
  }
  gh secret set $Name --body $Value
  Write-Host "  OK   $Name" -ForegroundColor Green
}

Write-Host "==> Setting GitHub Actions secrets..."

# SSH / server access
$port = if ($deploy["JETHOST_SSH_PORT"]) { $deploy["JETHOST_SSH_PORT"] } else { "1022" }
Set-Secret "JETHOST_SSH_HOST" $deploy["JETHOST_SSH_HOST"]
Set-Secret "JETHOST_SSH_USER" $deploy["JETHOST_SSH_USER"]
Set-Secret "JETHOST_SSH_PORT" $port
Set-Secret "JETHOST_APP_DIR"  ($deploy["JETHOST_APP_DIR"] ?? "pamporovo-villa")

$keyPath = $deploy["JETHOST_SSH_KEY"]
if ($keyPath -and (Test-Path $keyPath)) {
  Set-Secret "JETHOST_SSH_KEY" (Get-Content -Raw $keyPath)
} else {
  Write-Host "  SKIP JETHOST_SSH_KEY (file not found: $keyPath)" -ForegroundColor Yellow
}

# App secrets (from .env.production.local generated by secrets:prod)
Set-Secret "DATABASE_URL"          $deploy["DATABASE_URL"]
Set-Secret "SITE_URL"              $deploy["SITE_URL"]
Set-Secret "JWT_SECRET"            $prod["JWT_SECRET"]
Set-Secret "MASTER_ADMIN_PASSWORD" $prod["MASTER_ADMIN_PASSWORD"]
Set-Secret "VAPID_PUBLIC_KEY"      $prod["VAPID_PUBLIC_KEY"]
Set-Secret "VAPID_PRIVATE_KEY"     $prod["VAPID_PRIVATE_KEY"]

Write-Host ""
Write-Host "Done! GitHub Actions will deploy automatically on push to main." -ForegroundColor Green
Write-Host "Workflow: .github/workflows/deploy.yml"
